Module6 task1
htmlacademy-yii/1181399-task-force-1 pull request #11
Opened 2020-09-04 14:21 UTC by windstep

2020-09-06 12:49 UTC, frexin requested changes

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +    private function getTasks(array $searchFields)
Раз у тебя есть класс для формы, то логично туда перенести всю логику поиска. В контролере такое лучше не держать

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +        $searchFields = [
Вот это лишнее. Все поля, доступные для поиска, итак задаются в rules модели

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +        if (isset($searchFields['remote']) && $searchFields['remote']) {
Вместо этих условий можно использовать просто [andFilterWhere](https://www.yiiframework.com/doc/api/2.0/yii-db-queryinterface#andFilterWhere()-detail)

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +        if (isset($searchFields['withoutApplications']) && $searchFields['withoutApplications']) {
`if ($request->withoutApplications) { ... }`

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +            $tasks->leftJoin('applications', 'applications.task_id = id')
У тебя связь с applications уже прописана на уровне модели. Незачем тут указывать условие объединения. Также этот запрос вызовет Integrity constraint violation.
Достаточно просто заменить на `joinWith('applications')`

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +            $tasks->andWhere(['like', 'title', "%$name%"]);
andFilterWhere

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +            ->where(['status' => $searchFields['status'] ?? Task::STATUS_NEW])
Здесь нужно явно указать таблицу или алиас, потому что в противном случае при поиске будет 
Integrity constraint violation

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/TasksController.php
> +use Cassandra\Exception\ValidationException;
Это откуда?

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/UsersController.php
>      public function actionIndex()
Пожалуйста, посмотри все мои комментарии по странице tasks и сделай тут все сообразно

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/UsersController.php
> +        if (!$request->validate()) {
В задании сказано, что валидация не требуется. Но в любом случае, переадресация на другую страницу точно не нужна

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/UsersController.php
> +            ->groupBy('users.id');
`ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'task_force.tasks.created_at' which is not functionally dependent on columns in GROUP BY clause;`

2020-09-06 12:49 UTC, frexin commented on frontend/controllers/UsersController.php
>              ->select(
Я бы не стал пытаться вытащить всю информацию сразу внутри одного запроса через под-запросы. Ты можешь добавить relations-методы внутри модели пользователя и получать эти показатели отдельными запросами

2020-09-06 13:51 UTC, windstep commented on frontend/controllers/UsersController.php
> +            ->groupBy('users.id');
Не воспроизводится от слова совсем.

2020-09-09 07:48 UTC, frexin requested changes

2020-09-09 07:48 UTC, frexin commented on frontend/models/requests/UsersSearchForm.php
> +        var_dump($users->prepare(\Yii::$app->db->queryBuilder)->createCommand()->rawSql);
Вот это, наверное, лишнее. Надо убрать

2020-09-09 07:49 UTC, merged

2020-09-09 08:52 UTC, windstep commented on frontend/models/requests/UsersSearchForm.php
> +        var_dump($users->prepare(\Yii::$app->db->queryBuilder)->createCommand()->rawSql);
Упс. Случайно пролезло.