Добавил возможность регистрации.
htmlacademy-yii/1181399-task-force-1 pull request #13
Opened 2020-09-15 04:33 UTC by windstep

2020-09-15 07:28 UTC, frexin requested changes

2020-09-15 07:28 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +        if (Yii::$app->request->method === 'POST') {
Можно заменить на 
`Yii::$app->request->isPost`

2020-09-15 07:28 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +            if (!$request->validate()) {
Это условие можно упростить и проверять только на успешную валидацию

2020-09-15 07:28 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +        $request = new RegistrationForm();
Все еще не понимаю почему ты так называешь объекты формы

2020-09-15 07:28 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +                return $this->redirect('/');
Лучше заменить на `$this->goHome()`

2020-09-15 07:28 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +        $user->password = password_hash($request->password, PASSWORD_DEFAULT);
Лучше заменить на `Yii::$app->security->generatePasswordHash()`

2020-09-15 07:28 UTC, frexin commented on frontend/models/requests/RegistrationForm.php
> +        return [
Не указаны обязательные поля, нет проверки длины пароля, нет проверки города

2020-09-15 07:28 UTC, frexin commented on frontend/models/requests/RegistrationForm.php
> +class RegistrationForm extends Model
Вообще говоря, в этом классе нет необходимости. Ты мог описать все правила внутри модели пользователя, а так у тебя получается дублирование.

2020-09-15 07:28 UTC, frexin commented on frontend/views/registration/register.php
> +        <?= \yii\helpers\BaseHtml::activeInput('text', $request, 'email', ['class' => 'input textarea']) ?>
Нужно заменить на activeField, потому что с activeInput ты не можешь показать ошибки валидации полей, что требуется по заданию и ТЗ.

2020-09-15 07:28 UTC, frexin commented on frontend/views/layouts/main.php
> +            <?php if(!isset($user) || $user === null): ?>
Здесь нужно условие на проверку залогиненности пользователя через глобальный объект user

2020-09-17 15:38 UTC, frexin commented on frontend/views/layouts/main.php
> +            <?php if(!isset($user) || $user === null): ?>
Не исправлено

2020-09-17 15:38 UTC, frexin commented on frontend/models/requests/RegistrationForm.php
> +        return [
Не исправлено

2020-09-17 15:41 UTC, frexin requested changes

2020-09-17 15:41 UTC, frexin commented on frontend/controllers/RegistrationController.php
> +            if (!$request->validate()) {
У тебя сейчас регистрация пользователя выполняется при ошибках валидации

2020-09-17 15:41 UTC, frexin commented on frontend/models/requests/RegistrationForm.php
> +    public $email;
Задавать эти публичные свойства нет необходимости

2020-09-17 15:49 UTC, frexin requested changes

2020-09-17 15:49 UTC, frexin commented on frontend/views/layouts/main.php
> +            <?php if(!\yii\web\User::isGuest): ?>
Надо обращаться через контейнер:
`Yii::$app->user->isGuest`

2020-09-17 15:49 UTC, merged

2020-09-23 04:59 UTC, windstep commented on frontend/models/requests/RegistrationForm.php
> +    public $email;
Вылетает ошибка `Getting unknown property ...`