Сделал базу для работы с rest
htmlacademy-yii/1181399-task-force-1 pull request #18
Opened 2020-10-06 05:07 UTC by windstep

2020-10-06 05:17 UTC, frexin requested changes

2020-10-06 05:17 UTC, frexin commented on common/config/main.php
> +                'POST api/messages/<taskId:\d+>' => 'api/messages/create',
Это лишнее

2020-10-06 05:17 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +    public function actionView($id)
Этот метод не нужен

2020-10-06 05:17 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +class MessagesController extends Controller
Наследование должно быть от ActiveController

2020-10-06 05:17 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +    public function actionCreate($id)
$id здесь зачем?

2020-10-06 05:17 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +    public function actionCreate($id)
В целом метод не нужен скорее всего

2020-10-06 12:44 UTC, frexin requested changes

2020-10-06 12:44 UTC, frexin commented on frontend/models/Message.php
> +    public function beforeValidate()
Вот это тебе уже не нужно

2020-10-06 12:44 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +            ['message', 'safe'],
Добавить task_id

2020-10-07 07:26 UTC, frexin requested changes

2020-10-07 07:26 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +class MessagesController extends ActiveController
Аутентификацию надо настроить глобально для всего контроллера, как у тебя сделано в других местах.

2020-10-07 07:26 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +    public function behaviors()
Это все лишнее: ты дублируешь правила валидации, которые уже есть в модели.

2020-10-07 07:26 UTC, frexin commented on frontend/modules/api/controllers/TasksController.php
> +        return Task::find()->where(['=', 'author_id', \Yii::$app->user->getId()])
Почему бы просто не вернуть все сообщения для данного задания?

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +class MessageCreateRequest extends ActiveRecord
Я бы посоветовал отнаследоваться от Message, тогда нужно будет внести следующие изменения:

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +    public $task_id;
Убрать

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +    public function rules()
Убрать

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +    public function save($runValidation = true, $attributeNames = null)
Заменить на beforeValidate

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +        if (!$this->validate()) {
Убрать

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +        $userId = Yii::$app->user->getId() ?? 21;
Что за 21?

2020-10-07 07:26 UTC, frexin commented on frontend/models/requests/MessageCreateRequest.php
> +        $message->recipient_id = $task->author_id === $userId ? $task->author_id : $task->executor_id;
Назначать в саму модель

2020-10-07 09:04 UTC, windstep commented on frontend/modules/api/controllers/TasksController.php
> +        return Task::find()->where(['=', 'author_id', \Yii::$app->user->getId()])
В смысле? Это для первой части задания - вернуть все задачи...
https://taskforce.docs.apiary.io/#reference/0/0/0

2020-10-07 09:05 UTC, windstep commented on frontend/modules/api/controllers/MessagesController.php
> +    public function behaviors()
Нет. В модели нет правил валидации доступа к странице. В частности - проверки, что сообщение отправляет автор/исполнитель. И получает сообщение автор или исполнитель.

2020-10-07 14:07 UTC, frexin commented on frontend/modules/api/controllers/TasksController.php
> +        return Task::find()->where(['=', 'author_id', \Yii::$app->user->getId()])
Сорян, тут я тупанул. Ты прав

2020-10-11 12:07 UTC, frexin requested changes

2020-10-11 12:07 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +        if (!Yii::$app->request->get('task_id') && !Yii::$app->request->post('task_id')) {
Это лишние проверки. К тому же непонятно что они проверяют: это условие пропускает отсутствующий task_id в посте при создании сообщения и также пропускает отсутствующий task_id в гете при чтении сообщений. К тому же, проверка на существование task_id в GET есть в действии actionIndex, а существование task_id в POST проверяется в правилах модели Message...

2020-10-11 12:07 UTC, frexin commented on frontend/modules/api/controllers/MessagesController.php
> +        if ($task->author_id !== $userId || $task->executor_id !== $userId) {
Это условие не разрещает автору задания читать сообщения из своего задания.

2020-10-12 06:58 UTC, merged